### ISSUE TITLE
Fix the loopings on click of the arrows

### ISSUE THREAD

**Issue by meghannfh** [doanaminh/breathOfTheWIldAPI#19]
The loop is counting incorrectly after switching directions.
For example, forward > forward > backward < should console.log as 1, 2, 1 but instead it logs 1, 2, 3 and then finally on the second backward click it will count-- 

You can't loop backward past index 0 or past the last index back to the beginning. 

- [ ] Need to find a way to do indefinite looping on click in either direction.

**Comment by doanaminh** [comment]
A great solution to fix the looping issue, Meg!
